const types = {
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_ERROR: "ADD_PRODUCT_ERROR",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",
    GET_EDIT_PRODUCT: "GET_EDIT_PRODUCT",
    EDIT_PRODUCT: "EDIT_PRODUCT",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_ERROR: "EDIT_PRODUCT_ERROR",
    REGISTER_USER: "REGISTER_USER",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_ERROR: "LOGIN_USER_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    CLEAR_STATE: "CLEAR_STATE",
    SORT_BY_NAME: "SORT_BY_NAME"
}

export default types